{% set version = "4.4.0" %}

package:
  name: pexpect
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pexpect/pexpect-{{ version }}.tar.gz
  sha256: 67b85a1565968e3d5b5e7c9283caddc90c3947a2625bed1905be27bd5a03e47d

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - ptyprocess  # [not win]

test:
  imports:
    - pexpect

about:
  home: http://pexpect.sourceforge.net/
  license: ISC
  summary: 'Pexpect makes Python a better tool for controlling other applications.'

extra:
  recipe-maintainers:
    - jquast
    - pelson
    - takluyver
    - ocefpaf
