{% set version = "4.5.0" %}

package:
  name: pexpect
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pexpect/pexpect-{{ version }}.tar.gz
  sha256: 9f8eb3277716a01faafaba553d629d3d60a1a624c7cf45daa600d2148c30020c

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - ptyprocess  # [not win]

test:
  imports:
    - pexpect

about:
  home: http://pexpect.sourceforge.net/
  license: ISC
  summary: 'Pexpect makes Python a better tool for controlling other applications.'

extra:
  recipe-maintainers:
    - jquast
    - pelson
    - takluyver
    - ocefpaf
