{% set name = "pexpect" %}
{% set version = "4.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: ee7d41123f3c9911050ea2c2dac107568dc43b2d3b0c7557a33212c398ead30f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - ptyprocess >=0.5

{% set ignore_tests = "" %}
# Randomly hanging on osx
{% set ignore_tests = " --ignore=tests/test_expect.py" %}  # [osx]
# OSError: [Errno 57] Socket is not connected
{% set ignore_tests = ignore_tests + " --ignore=tests/test_socket.py --ignore=tests/test_socket_fd.py --ignore=tests/test_socket_pexpect.py" %}  # [osx]

# AssertionError: bash: man: command not found
{% set tests_to_skip = "test_pager_as_cat" %}
# pexpect.exceptions.ExceptionPexpect: The command was not found or was not executable: zsh
{% set tests_to_skip = tests_to_skip + " or test_zsh" %}
# Exception: Unexpected output For more details, please visit https://support.apple.com/kb/HT208050.
{% set tests_to_skip = tests_to_skip + " or test_run_event_as_function or test_run_event_as_method" %}  # [osx]
# assert res.strip().splitlines() == ['0', '1', '2']
{% set tests_to_skip = tests_to_skip + " or test_no_change_prompt" %}  # [osx]
# assert res.strip() == '11'
{% set tests_to_skip = tests_to_skip + " or test_python" %}  # [osx]
# pexpect.spawn uses env argument when running child process -> self.assertEqual(child.exitstatus, 0) -> AssertionError: None != 0
{% set tests_to_skip = tests_to_skip + " or test_spawn_uses_env" %}  # [osx]

test:
  source_files:
    - tests
  imports:
    - pexpect
    - pexpect.popen_spawn
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v {{ ignore_tests }} -k "not ({{ tests_to_skip }})" tests  # [not win]
    # Most tests are not working on Windows: https://github.com/pexpect/pexpect/issues/321
    - pytest -v tests/test_socket_pexpect.py tests/test_screen.py tests/test_filedescriptor.py tests/test_ansi.py tests/test_FSM.py  # [win]
    
about:
  home: https://pexpect.sourceforge.net
  license: ISC
  license_family: Other
  license_file: LICENSE
  summary: Pexpect makes Python a better tool for controlling other applications.
  description: |
    Pexpect is a pure Python module for spawning child applications; controlling them; 
    and responding to expected patterns in their output. Pexpect works like Don Libes’ Expect. 
    Pexpect allows your script to spawn a child application and control it as if a human were typing commands.
  doc_url: https://pexpect.readthedocs.org
  dev_url: https://github.com/pexpect/pexpect

extra:
  recipe-maintainers:
    - jquast
    - pelson
    - takluyver
    - ocefpaf