travis:
  secure:
    BINSTAR_TOKEN: cjODpuoCZTgL4/kw/h0r+9RVQMlnjHEKdmqEYLMXkTEdZhFYq6PC5HG+3tyKq/KphPcbcIuF9vtXeWXrp7Hx/BqJG5P65Um7tZoXTW3i/gYMESavACUzPI+6gaM0U3QlcZRFYx04yTrpd/9SIsFW/S7GfSE81C2n3Cw/fYOMSZ+jdfbzaU3+CJJtJdPVMo0v1kySeOKmxy1Xl1cPvHDYOY6wdzvZxOdXSJa4mUeWpaMgcPp7E6HisOLj3By5B8wyxTkLHgw/xu17GIs/41FTVQr4u8SZBOqhCQc9AM8pY+vjLYYHltTg03u8eMgFDABkLeEfFg84FrJl3KbrD6UZE7OBRP+sfxtL74kU2N+4wTkxwZtv9HuWjKvQyFL6CG+xXbAq06Y0FhpAQDGPzqzHxOyFfS14I//c13KgkbJPlmvvZ41Od+sNZCygbtJBeU5rvZzge3XTzdNt9iRQGo1rvhM6JNc4xqpCNWoA+P14DyInWvXtF3cBHQKkIlFMnDiuZaCJlYDuAGgnovNm0Zd4zI5BTFnc5JdcLKEAv6OY1yBC3g65TjFG2cS1ZK90DPD/1iMJjLTqyVTNaw89DLPn+Ur+bXuXTCr/lcikc2xIf7PpHXItlJLiVOI2ygZN4oYteA2sWvcBiODW5YK0nSWx2AozwHbXal7leQAzkZgFWBc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
